config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'tagsearches' => 'tagsearches#search'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'search_date' => 'users#search'
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :notifications, only:[:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end
  
  def destroy
   comment = BookComment.find(params[:id])
   comment.destroy
   redirect_to request.referer
  end
  
  private
  
    def book_comment_params
      params.require(:book_comment).permit(:comment)
    end
  
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
<!--コメント数表示-->
<p>コメント数：<%= book.book_comments.count %></p>

app/views/book_comments/_form.html.erb
<div class="form-group">
  <%= form_with model: [book, book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', class: "form-control mb-2", placeholder: "" %>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(user.id) do %>
          <%= image_tag book_comment.user.get_profile_image(50,50) %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
        <td>
          <%= link_to book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-sm btn-danger" do %>
            Destroy
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>