config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'tagsearches' => 'tagsearches#search'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'search_date' => 'users#search'
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :notifications, only:[:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :profile_image     
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  # 一人のユーザに対してフォローしているのは複数
  # モデルの関連付け→任意の名前、クラス→中間テーブル、外部キー→フォローするユーザid、
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # ユーザがフォローしているユーザ一覧を表示のための関連付け
  has_many :followings, through: :active_relationships, source: :followed
  # 一人のユーザに対して複数のフォロワーが存在する
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # ユーザのフォロワーの一覧を取得するための関連付け
  has_many :followers, through: :passive_relationships, source: :follower
  
  # 指定ユーザのフォロー
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  # 指定ユーザのフォロー解除
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  # 指定ユーザをフォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  GUEST_USER_EMAIL = "guest@example.com"
    def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
    end
    def guest_user?
      email == GUEST_USER_EMAIL
    end
  
  
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  
  
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # user検索
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit, :update]
  def index
    @user = current_user
    @users = User.all
    @book = Book.new

  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  # 指定日の投稿数を表示
  def search
    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)

  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
        redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(80,80)%></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td>
            <!--フォローボタン-->
            <% if current_user != user %>
              <%= render 'relationships/btn', user: user %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/users/_info.html.erb
<h2>User info</h2>

<table class="table">
  <tbody>
    <tr><%= image_tag user.get_profile_image(100,100) %></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>  
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>
  </tbody>
</table>
<% unless user.guest_user? %>
  <div class="row">
    <% if current_user != user %>
     <%= render 'relationships/btn', user: user %>
    <% else %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<!--検索フォーム-->
<div class="row justify-content-center my-3">
  <div class="col-auto">
    <!--フォーム-->
    <%= form_with url: user_search_date_path(user), method: :get, local: false do |f| %>
      <div class="input-group">
        <%= f.date_field :created_at, class: "form-control" %>
        <div class="input-group-append">
          <%= f.submit "検索", class: "btn btn-info" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="daily_posts_table">
</div>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card">
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j ( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 pc-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/errors', obj: @user %>
        <%= form_with model: @user do |f|  %>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control name', placeholder: "" %>
        </div>
        <div class="form-group">
          <%= f.label :Image %><br>
          <%= f.file_field :profile_image, placeholder: "form-control user_image", accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %><br>
          <%= f.text_area :introduction, class: 'form-control introduction', placeholder: "" %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0 mt-3">
 <div class="row">
    <div class="col-md-3">
      <!--ユーザ情報-->
      <%= render 'users/info', user: @user %>
      <!--投稿フォーム-->
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0 mt-3">
 <div class="row">
    <div class="col-md-3">
      <!--ユーザ情報-->
      <%= render 'users/info', user: @user %>
      <!--投稿フォーム-->
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/index", books: @books %>
    </div>
  </div>
  <%= render 'search', user: @user %>
</div>