config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'tagsearches' => 'tagsearches#search'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'search_date' => 'users#search'
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :notifications, only:[:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :category, presence: true

  # ユーザが特定の投稿にいいねをしているか判定する
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  # book検索
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('name LIKE ?', '%' + content)
    else
      Book.where('name LIKE ?', '%' + content + '%')
    end
  end
  # 通知の作成
  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end

  # 新着順
  scope :latest, -> {order(created_at: :desc)}
  # 古い順
  scope :old, -> {order(created_at: :asc)}
  # 評価順
  scope :star_count, -> {order(star: :desc)}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user

    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
    redirect_to books_path
    else
      render :index
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)

  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless current_user.id == book.user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<!--投稿欄-->

<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f|  %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control book_title', placeholder: "" %>
  </div>
  <div class="form-group">
    <%= f.label :Opinion %><br>
    <%= f.text_area :body, class: 'form-control book_body', placeholder:"" %>
  </div>

  <% if book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function(){
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "static_rate", book: book %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Category %>
    <%= f.text_field :category, class: 'form-control book_category' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book) do %>
            <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        <td>
          <%= link_to book.category, tagsearches_path(content: book.category) %>
        </td>
        <!--いいね表示-->
        <td id="favorite_btn_<%= book.id %>">
          <%= render 'favorites/btn', book: book %>
        </td>

        <!--コメント数表示-->
        <td>
          <%= render 'book_comments/count', book: book %>
        </td>

        <td>
          <%= render 'books/static.rate', book: book %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static.rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
  $(document).on('turbolinks:load', function(){
    let elem = document.querySelector('#star_<%= book.id %>');
    if (elem == null) return;

    elem.innerHTML = "";
    let opt = {
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      score: "<%= book.star %>",
      readOnly: true,
    };
    raty(elem, opt);
  });
</script>

app/views/books/edit.html.erb
<!--Book編集ページ-->
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 pc-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errors', obj: @book %>
      <%= form_with model: @book do |f|  %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: 'form-control book_title', placeholder: "" %>
        </div>
        <div class="form-group">
          <%= f.label :Opinion %><br>
          <%= f.text_area :body, class: 'form-control book_body', placeholder:"" %>
        </div>
        <div class="form-group">
          <%= render 'books/static.rate', book: @book %>
        </div>
        <div class="form-group">
          <%= f.label :Category %>
          <%= f.text_field :category, class: 'form-control book_category' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
      <!--show→Book詳細ページへ、Back→Book一覧ページへ-->
      <div>
        <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
      </div>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <%= render 'layouts/errors', obj: @book %>
 <div class="row">
    <div class="col-md-3">

      <!--ユーザ情報-->
      <%= render 'users/info', user: @user %>
      <!--投稿フォーム-->
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(latest: "true") %>
      |<%= link_to "古い順", books_path(old: "true") %>
      |<%= link_to "評価の高い順", books_path(star_count: "true") %>
      <!--本の一覧表示-->
      <%= render "books/index", books: @books, book: @book %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0 mt-3">
 <div class="row">
    <div class="col-md-3">

      <!--ユーザ情報-->
      <%= render 'users/info', user: @user %>
      <!--投稿フォーム-->
      <%= render 'books/form', book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <!--本の詳細表示-->
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(30,30) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.category, tagsearches_path(content: @book.category) %>
            </td>
            <td><%= @book.body %></td>
            <!--いいね機能の表示設定-->
            <td id="favorite_btn_<%= @book.id %>">
              <%= render 'favorites/btn', book: @book %>
            </td>
            <!--コメント数の表示設定-->
            <td>
              <%= render 'book_comments/count', book: @book %>
            </td>
            <td>
              <!--評価数-->
              <%= render 'books/static.rate', book: @book %>
            </td>
            <!--ログインユーザ分のみeditとdestroyを表示する-->
            <% if @book.user == current_user %>
              <td>
                <%= link_to edit_book_path(@book), class: "btn btn-sm btn-success" do %>
                  Edit
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" do %>
                  Destroy
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <!--コメント一覧表示-->
      <%= render 'book_comments/index', book: @book, user: @user %>
      <!--コメント投稿フォーム-->
      <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>