config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'tagsearches' => 'tagsearches#search'
  resources :users, only: [:index, :show, :edit, :update] do
    get 'search_date' => 'users#search'
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :notifications, only:[:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<div>
  <% if obj.errors.any? %>
    <h3><%= obj.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  <div>
</footer>

app/views/layouts/_header.html.erb
<header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span></a>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item text-light">
                  <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-book-open"></i> Books
                  <% end %>
                </li>
                <li class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expended="false">
                    Notification
                    <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <% if current_user.notifications.where(read: false).any? %>
                      <small class="dropdown-item disabled">直近5件の未読の通知を表示しています。</small>
                      <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                        <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                      <% end %>
                    <% else %>
                      <span class="dropdown-item disabled">未読の通知はありません</span>
                    <% end %>
                  </div>
                </li>
                <li class="nav-item">
                  <%= link_to  destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-right-from-bracket"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item text-light">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to home_about_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-right-to-bracket"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/_search.html.erb
<div class="search_form">
  <table align="center">
    <tr>
      <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <td><%= f.text_field :content %></td>
          <td><%= f.select :model, options_for_select({"User" => "user", "Book" => "book" }) %></td>
          <td><%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %></td>
          <td><%= f.submit "検索", class: "btn btn-sm btn-primary" %></td>
        <% end %>
      </div>
    </tr>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22nd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0e58e38434.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <% if user_signed_in? %>
        <div class="d-flex justify-content-center my-3">
          <%= render 'layouts/search' %>
          <%= render 'tagsearches/tagsearch' %>
        </div>
      <% end %>
      <div>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>